controller_manager:
  ros__parameters:
    update_rate: 100 # Hz

    velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    forward_position_controller:
      type: forward_command_controller/ForwardCommandController

forward_position_controller:
  ros__parameters:
    joints:
      - lf_steering_hinge_joint
      - rf_steering_hinge_joint
    interface_name: position

velocity_controller:
  ros__parameters:
    joints:
      - lr_wheel_joint
      - rr_wheel_joint
      - lf_wheel_joint
      - rf_wheel_joint
    command_interfaces:
      - velocity
    state_interfaces:
      - position
      - velocity
